<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="11" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="5324" started-at="2019-12-09T20:35:51Z" finished-at="2019-12-09T20:35:56Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="5324" started-at="2019-12-09T20:35:51Z" finished-at="2019-12-09T20:35:56Z">
      <class name="com.apex.customerServiceTest.GetTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="setup" is-config="true" duration-ms="19" started-at="2019-12-09T12:35:53Z" finished-at="2019-12-09T12:35:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="testwithAsterik()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="testwithAsterik" duration-ms="463" started-at="2019-12-09T12:35:53Z" finished-at="2019-12-09T12:35:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testwithAsterik -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="cleanUp" is-config="true" duration-ms="0" started-at="2019-12-09T12:35:53Z" finished-at="2019-12-09T12:35:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="setup" is-config="true" duration-ms="0" started-at="2019-12-09T12:35:53Z" finished-at="2019-12-09T12:35:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="testwithHashSymbol()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="testwithHashSymbol" duration-ms="4" started-at="2019-12-09T12:35:53Z" finished-at="2019-12-09T12:35:53Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Illegal character in fragment at index 46: http://www.thomas-bayer.com/sqlrest/CUSTOMER/##]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Illegal character in fragment at index 46: http://www.thomas-bayer.com/sqlrest/CUSTOMER/##
	at java.net.URI.create(URI.java:852)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
	at com.apex.api.core.ApexHttpUtil.sendAndReceiveGETMessage(ApexHttpUtil.java:33)
	at com.apex.customerServiceTest.GetTest.testwithHashSymbol(GetTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.net.URISyntaxException: Illegal character in fragment at index 46: http://www.thomas-bayer.com/sqlrest/CUSTOMER/##
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3067)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 37 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testwithHashSymbol -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="cleanUp" is-config="true" duration-ms="1" started-at="2019-12-09T12:35:53Z" finished-at="2019-12-09T12:35:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="setup" is-config="true" duration-ms="0" started-at="2019-12-09T12:35:53Z" finished-at="2019-12-09T12:35:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="testwithInvalidData()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="testwithInvalidData" duration-ms="399" started-at="2019-12-09T12:35:53Z" finished-at="2019-12-09T12:35:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testwithInvalidData -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="cleanUp" is-config="true" duration-ms="0" started-at="2019-12-09T12:35:54Z" finished-at="2019-12-09T12:35:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method status="PASS" signature="testwithNegativeNumber()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="testwithNegativeNumber" duration-ms="381" started-at="2019-12-09T12:35:54Z" finished-at="2019-12-09T12:35:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testwithNegativeNumber -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="setup" is-config="true" duration-ms="0" started-at="2019-12-09T12:35:54Z" finished-at="2019-12-09T12:35:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="cleanUp" is-config="true" duration-ms="1" started-at="2019-12-09T12:35:54Z" finished-at="2019-12-09T12:35:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="setup" is-config="true" duration-ms="0" started-at="2019-12-09T12:35:54Z" finished-at="2019-12-09T12:35:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="testwithPositiveNumber()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="testwithPositiveNumber" duration-ms="386" started-at="2019-12-09T12:35:54Z" finished-at="2019-12-09T12:35:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.apex.api.core.ApexHttpValidator.performCommonResponseValidations(ApexHttpValidator.java:8)
	at com.apex.customerServiceTest.GetTest.testwithPositiveNumber(GetTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testwithPositiveNumber -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="cleanUp" is-config="true" duration-ms="0" started-at="2019-12-09T12:35:55Z" finished-at="2019-12-09T12:35:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="setup" is-config="true" duration-ms="0" started-at="2019-12-09T12:35:55Z" finished-at="2019-12-09T12:35:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="testwithSpace()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="testwithSpace" duration-ms="2" started-at="2019-12-09T12:35:55Z" finished-at="2019-12-09T12:35:55Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Illegal character in path at index 45: http://www.thomas-bayer.com/sqlrest/CUSTOMER/  ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Illegal character in path at index 45: http://www.thomas-bayer.com/sqlrest/CUSTOMER/  
	at java.net.URI.create(URI.java:852)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
	at com.apex.api.core.ApexHttpUtil.sendAndReceiveGETMessage(ApexHttpUtil.java:33)
	at com.apex.customerServiceTest.GetTest.testwithSpace(GetTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.net.URISyntaxException: Illegal character in path at index 45: http://www.thomas-bayer.com/sqlrest/CUSTOMER/  
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 37 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testwithSpace -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="cleanUp" is-config="true" duration-ms="0" started-at="2019-12-09T12:35:55Z" finished-at="2019-12-09T12:35:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method status="PASS" signature="testwithSpecialCharacters()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="testwithSpecialCharacters" duration-ms="385" started-at="2019-12-09T12:35:55Z" finished-at="2019-12-09T12:35:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testwithSpecialCharacters -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="setup" is-config="true" duration-ms="0" started-at="2019-12-09T12:35:55Z" finished-at="2019-12-09T12:35:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="cleanUp" is-config="true" duration-ms="1" started-at="2019-12-09T12:35:55Z" finished-at="2019-12-09T12:35:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method status="FAIL" signature="testwithZeroes()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="testwithZeroes" duration-ms="385" started-at="2019-12-09T12:35:55Z" finished-at="2019-12-09T12:35:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.apex.api.core.ApexHttpValidator.performCommonResponseValidations(ApexHttpValidator.java:8)
	at com.apex.customerServiceTest.GetTest.testwithZeroes(GetTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testwithZeroes -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="setup" is-config="true" duration-ms="0" started-at="2019-12-09T12:35:55Z" finished-at="2019-12-09T12:35:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.apex.customerServiceTest.GetTest@511baa65]" name="cleanUp" is-config="true" duration-ms="0" started-at="2019-12-09T12:35:55Z" finished-at="2019-12-09T12:35:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- com.apex.customerServiceTest.GetTest -->
      <class name="com.apex.customerServiceTest.DeleteTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.apex.customerServiceTest.DeleteTest@30c7da1e]" name="setup" is-config="true" duration-ms="20" started-at="2019-12-09T12:35:51Z" finished-at="2019-12-09T12:35:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="deleteRecord()[pri:0, instance:com.apex.customerServiceTest.DeleteTest@30c7da1e]" name="deleteRecord" duration-ms="1975" started-at="2019-12-09T12:35:51Z" finished-at="2019-12-09T12:35:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.apex.api.core.ApexHttpValidator.performCommonResponseValidations(ApexHttpValidator.java:8)
	at com.apex.customerServiceTest.DeleteTest.deleteRecord(DeleteTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteRecord -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.apex.customerServiceTest.DeleteTest@30c7da1e]" name="cleanUp" is-config="true" duration-ms="6" started-at="2019-12-09T12:35:53Z" finished-at="2019-12-09T12:35:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- com.apex.customerServiceTest.DeleteTest -->
      <class name="com.apex.customerServiceTest.PutTest">
        <test-method status="PASS" signature="updatePositiveNumberWithPut()[pri:0, instance:com.apex.customerServiceTest.PutTest@340f438e]" name="updatePositiveNumberWithPut" duration-ms="410" started-at="2019-12-09T12:35:56Z" finished-at="2019-12-09T12:35:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updatePositiveNumberWithPut -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.apex.customerServiceTest.PutTest@340f438e]" name="setup" is-config="true" duration-ms="0" started-at="2019-12-09T12:35:56Z" finished-at="2019-12-09T12:35:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.apex.customerServiceTest.PutTest@340f438e]" name="cleanUp" is-config="true" duration-ms="0" started-at="2019-12-09T12:35:56Z" finished-at="2019-12-09T12:35:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- com.apex.customerServiceTest.PutTest -->
      <class name="com.apex.customerServiceTest.PostTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.apex.customerServiceTest.PostTest@5b464ce8]" name="setup" is-config="true" duration-ms="1" started-at="2019-12-09T12:35:55Z" finished-at="2019-12-09T12:35:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="sendPOST()[pri:0, instance:com.apex.customerServiceTest.PostTest@5b464ce8]" name="sendPOST" duration-ms="390" started-at="2019-12-09T12:35:55Z" finished-at="2019-12-09T12:35:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendPOST -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.apex.customerServiceTest.PostTest@5b464ce8]" name="cleanUp" is-config="true" duration-ms="0" started-at="2019-12-09T12:35:56Z" finished-at="2019-12-09T12:35:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- com.apex.customerServiceTest.PostTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
